export const EXAMLE_PROMPTS = [
    "A futuristic cyberpunk city at night, neon lights reflecting on wet streets, towering skyscrapers with holographic ads, a lone figure in a high-tech coat walking past neon signs, cinematic lighting, 8K ultra-detailed.",
    "A majestic dragon soaring over a medieval castle at sunset, its scales shimmering in gold and red, fiery breath illuminating the clouds, highly detailed fantasy art, dramatic composition.",
    "An adorable kitten wearing a tiny astronaut helmet, floating in zero gravity with stars and Earth visible through a spaceship window, Pixar-style 3D rendering, soft lighting.",
    "A serene Japanese garden in autumn, vibrant red maple leaves covering stone paths, a wooden bridge over a koi pond, soft sunlight filtering through trees, Studio Ghibli-inspired watercolor style.",
    "A post-apocalyptic wasteland with rusted cars and overgrown vegetation, a stormy sky casting eerie green light, a masked scavenger holding a makeshift weapon, photorealistic textures.",
    "A steampunk airship flying above Victorian London, intricate brass gears and smokestacks, passengers in goggles and corsets leaning over the railing, sepia-toned with cinematic depth.",
    "A mystical elf archer standing on a tree branch in an enchanted forest, glowing blue tattoos on her skin, aiming at an unseen target, magical particles floating around, digital painting.",
    "A surreal landscape where giant jellyfish float through a sky of liquid gold, upside-down mountains in the distance, dreamlike atmosphere, vibrant colors, art by Moebius.",
    "A cybernetic samurai with a glowing katana, standing in a neon-lit alley, rain falling slowly as his visor displays targeting data, hyper-realistic cyberpunk aesthetic.",
    "A cozy cabin in the snowy woods, smoke rising from the chimney, warm light glowing through windows, northern lights dancing in the starry sky, Disney-style illustration.",
    "A terrifying cosmic horror entity emerging from a black hole, tentacles made of galaxies, eyes like supernovae, Lovecraftian style, dark and intricate artwork.",
    "A bustling alien marketplace on a desert planet, exotic creatures bartering under twin suns, stalls with glowing crystals and strange artifacts, sci-fi realism.",
    "A warrior queen riding a armored war rhino through a battlefield, flaming arrows streaking across the sky, epic fantasy composition, inspired by Frank Frazetta.",
    "A tiny wizard's workshop hidden inside a giant pumpkin, shelves filled with potions and spellbooks, a black cat sleeping near a cauldron, whimsical detailed illustration.",
    "A lone cowboy riding through a desert canyon at dusk, silhouetted against a blood-red sky, tumbleweeds rolling past, ultra-wide cinematic shot, Red Dead Redemption vibes.",
    "A futuristic Tokyo street in 2150, flying cars between holographic billboards, a neon umbrella reflecting pink and blue lights, Blade Runner meets anime aesthetics.",
    "A mermaid with bioluminescent scales resting on a coral throne, schools of tropical fish swirling around her, sunbeams piercing the deep ocean, Disney princess realism.",
    "A haunted Victorian mansion covered in ivy, lightning striking behind its broken windows, a ghostly figure visible in the doorway, gothic horror atmosphere.",
    "A battle-hardered orc blacksmith forging a fiery axe in a volcano's heart, sweat dripping onto molten metal, dark fantasy realism, detailed armor textures.",
    "A robot farmer tending to a field of glowing plants under a purple sky, a small solar-powered drone watering crops, sci-fi utopian illustration.",
    "A time traveler in steampunk gear stepping out of a clockwork portal into ancient Egypt, pyramids under construction in the background, intricate mashup of eras.",
    "A phoenix reborn from golden ashes, wings spreading wide in a cathedral of fire, ultra-detailed feathers and dynamic flames, symbolic artwork.",
    "A secret library hidden inside a giant tree, spiral staircases leading to floating books, ancient runes glowing softly, magical academic core.",
    "A pirate ship trapped in a giant ice crystal, frozen mid-battle with skeletons clutching swords, eerie blue lighting, fantasy adventure concept.",
    "A cybernetic fox with LED-lined fur running through a digital forest, binary code falling like leaves, synthwave color palette, glitch art effects.",
    "A goddess of the cosmos wearing a dress made of constellations, holding a dying star in her palms, ethereal and melancholic space art.",
    "A wild west town invaded by aliens, cowboys hiding behind saloon doors as a UFO hovers overhead, retro sci-fi movie poster style.",
    "A crystal cave filled with giant glowing mushrooms, a subterranean lake reflecting bioluminescent light, fantasy exploration scene.",
    "A samurai fighting a skeleton army in a moonlit bamboo forest, cherry blossoms swirling in the air, dynamic ink painting style.",
    "A postcard-like view of Santorini with white buildings and blue domes, sunset painting the sky in pastel hues, photorealistic travel shot.",
    "A mad scientist's lab with bubbling test tubes, a Frankenstein monster under a sheet, lightning flashing outside the window, gothic horror comedy.",
    "A futuristic mech suit covered in jungle vines, abandoned for centuries, a small animal nesting in its cockpit, post-human world concept.",
    "A Viking funeral at sea, a burning longship drifting toward the horizon under the northern lights, emotional and cinematic composition.",
    "A magical girl transforming with sparkling ribbons and cosmic energy, anime-style action pose, vibrant magical effects.",
    "A dystopian megacity where the rich live in floating skyscrapers while the poor crowd the polluted streets below, social commentary art.",
    "A witch's apothecary with hanging herbs, jars of eyeballs, and a black cauldron simmering, dark academia aesthetic, highly detailed.",
    "A parallel universe where cats rule the world, wearing tiny crowns and holding court in a grand palace, humorous and whimsical.",
    "A lone astronaut standing on Mars, planting a flag next to the ruins of an ancient alien civilization, cinematic sci-fi realism.",
    "A fairy-tale wedding in an enchanted forest, deer with floral antlers attending, fireflies forming a chandelier, romantic Disney-esque scene.",
    "A noir detective in a trench coat investigating a crime scene with glowing cybernetic evidence, rain-soaked neon alley, cinematic lighting.",
    "A colossal kaiju attacking a futuristic city, fighter jets swarming around it like bees, Godzilla-inspired epic destruction.",
    "A dwarven miner discovering a cavern filled with glowing crystals and gold veins, fantasy adventure illustration.",
    "A surrealist painting where the sky is made of liquid mercury, fish swimming through clouds, Salvador Dali meets Hayao Miyazaki.",
    "A cyberpunk hacker girl with neon tattoos and augmented reality glasses, typing on a holographic keyboard, purple and pink lighting.",
    "A mummy awakening in a modern museum, bandages unraveling as it steps out of its sarcophagus, horror-comedy concept.",
    "A steampunk submarine exploring the depths of an alien ocean, crew in brass diving suits encountering bioluminescent creatures.",
    "A celestial wolf made of stars running across the Milky Way, cosmic dust trailing behind it, mystical astronomy art.",
    "A post-war paradise where nature reclaims abandoned tanks and buildings, deer grazing beside rusted war machines, hopeful dystopia.",
    "A legendary sword embedded in a stone, surrounded by cherry blossoms, waiting for the chosen one, epic fantasy symbolism.",
];
