name: Build and Deploy

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build with secret
              run: npm run build
              env:
                  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
